import {
   Activity, Box, DollarSign, Megaphone, Scale, Users,
} from 'lucide-react';
import type { ReportCategory } from './useReportsState';

export const REPORT_CATEGORIES: ReportCategory[] = [
   { id: 'SALES', label: 'Sales & Revenue', color: '#10b981', icon: DollarSign, subReports: ['Daily Sales', 'Hourly Trends', 'Payment Mix', 'Cashier Summary', 'Refunds', 'Sales by Order Type', 'Sales by Item', 'Sales by Category', 'Discounts', 'Cancelled Orders', 'Sales by Source', 'Peak Hours Heatmap', 'Modifier Sales', 'Avg Ticket Trend', 'Sales Comparison', 'Slow-Moving Items', 'Revenue by Weekday', 'Void Items Log', 'Discounts by Cashier', 'Voids by Cashier', 'Menu Engineering', 'Daypart Analysis', 'Basket Analysis', 'Seasonality', 'Online vs Offline', 'Menu Cannibalization', 'Menu Item Lifecycle', 'Category Contribution', 'Time-to-First-Order'] },
   { id: 'FINANCE', label: 'Financials & VAT', color: '#f59e0b', icon: Scale, subReports: ['Z-Report / Fiscal', 'Profit & Loss (P&L)', 'Trial Balance', 'Balance Sheet', 'Expense Report', 'Top Expenses', 'Tips Report', 'Service Charge', 'Shift Summary', 'Food Cost % Trend', 'Cash Flow Forecast', 'Tax Compliance', 'E-Invoice Rejections', 'Audit Trail', 'Break-Even Analysis', 'Payment Reconciliation', 'Shift Profitability', 'Day-Close Variances', 'Treasury Cashbox', 'Custody Statement', 'Supplier Invoices'] },
   { id: 'INVENTORY', label: 'Inventory & Supply', color: '#06b6d4', icon: Box, subReports: ['COGS & Margin', 'Stock Counts', 'Stock Movement', 'Waste/Loss Log', 'Reorder Alerts', 'Expiring Batches', 'Actual vs Theoretical', 'Purchase History', 'Purchase Orders', 'Suppliers',    'Inventory Valuation', 'Supplier Price Tracking', 'Recipe Cost Alerts', 'ABC Classification', 'Dead Stock', 'Negative Stock', 'Optimal Pricing', 'Production Batches', 'Production Cost Variance', 'Butchery Yield', 'Inter-Branch Transfers', 'GRN Variance'] },
   { id: 'HR', label: 'HR & Payroll', color: '#0f766e', icon: Users, subReports: ['HR Executive Summary', 'Payroll Summary', 'Payroll Ledger', 'Attendance & Delays', 'Attendance Exceptions', 'Overtime Report', 'Staff Cost %', 'Sales per Labor Hour', 'Employee Productivity', 'Headcount & Turnover', 'Leave & Absence', 'Shift Tasks Completion'] },
   { id: 'CRM', label: 'Customers & CRM', color: '#ec4899', icon: Megaphone, subReports: ['Customer LTV', 'Campaign ROI', 'Customer Retention', 'New vs Returning', 'Customer Frequency', 'Customer Churn', 'Loyalty Points', 'Promotion Impact', 'Customer Journey Funnel', 'Complaints & SLA', 'Coupon Usage', 'WhatsApp Inbox'] },
   { id: 'OPS', label: 'Operations', color: '#3b82f6', icon: Activity, subReports: [   'Branch Performance', 'Order Preparation Time', 'Delivery Performance', 'Dine-in Tables', 'Unpaid Orders', 'Kitchen Performance', 'Kitchen Staff Performance', 'Table Turnover', 'Wait Time', 'Driver Utilization', 'Branch Comparison', 'Delivery Zone Analytics', 'Delivery Cost vs Revenue', 'Delivery SLA Alerts', '3rd Party vs In-House', 'Reservations & No-Show', 'Driver COD Settlement', 'Approval SLA', 'Platform Commissions', 'User Activity Log'] },
   { id: 'AI', label: 'AI & Predictive', color: '#6366f1', icon: Activity, subReports: ['Daily Flash Report', 'Demand Forecasting', 'Price Elasticity Simulator', 'Anomaly Detection', 'Channel Mix Trend'] },
];

export const REPORT_DISPLAY_LABELS: Record<string, string> = {
   'Sales & Revenue': 'المبيعات والإيرادات',
   'Financials & VAT': 'المالية والضرائب',
   'Inventory & Supply': 'المخزون والتوريد',
   'HR & Payroll': 'الموارد البشرية والرواتب',
   'Customers & CRM': 'العملاء والتسويق',
   Operations: 'التشغيل',
   'AI & Predictive': 'الذكاء والتحليلات التنبؤية',
   'Daily Sales': 'المبيعات اليومية',
   'Hourly Trends': 'اتجاهات المبيعات بالساعة',
   'Payment Mix': 'توزيع طرق الدفع',
   'Cashier Summary': 'ملخص الكاشير',
   Refunds: 'المرتجعات',
   'Sales by Order Type': 'المبيعات حسب نوع الطلب',
   'Sales by Item': 'المبيعات حسب الصنف',
   'Sales by Category': 'المبيعات حسب التصنيف',
   Discounts: 'الخصومات',
   'Cancelled Orders': 'الطلبات الملغاة',
   'Sales by Source': 'المبيعات حسب المصدر',
   'Peak Hours Heatmap': 'خريطة ساعات الذروة',
   'Modifier Sales': 'مبيعات الإضافات',
   'Avg Ticket Trend': 'اتجاه متوسط الفاتورة',
   'Sales Comparison': 'مقارنة المبيعات',
   'Slow-Moving Items': 'الأصناف بطيئة الحركة',
   'Revenue by Weekday': 'الإيراد حسب أيام الأسبوع',
   'Void Items Log': 'سجل الأصناف المحذوفة',
   'Discounts by Cashier': 'الخصومات حسب الكاشير',
   'Voids by Cashier': 'الملغي حسب الكاشير',
   'Unpaid Orders': 'طلبات غير مدفوعة',
   'Menu Engineering': 'هندسة المنيو',
   'Daypart Analysis': 'تحليل فترات اليوم',
   'Basket Analysis': 'تحليل سلة الشراء',
   Seasonality: 'الموسمية',
   'Online vs Offline': 'أونلاين مقابل داخل الفرع',
   'Menu Cannibalization': 'تداخل مبيعات أصناف المنيو',
   'Menu Item Lifecycle': 'دورة حياة صنف المنيو',
   'Category Contribution': 'مساهمة التصنيفات',
   'Time-to-First-Order': 'وقت أول طلب',
   'Z-Report / Fiscal': 'تقرير Z والضريبة',
   'Profit & Loss (P&L)': 'الأرباح والخسائر',
   'Trial Balance': 'ميزان المراجعة',
   'Expense Report': 'تقرير المصروفات',
   'Top Expenses': 'أعلى المصروفات',
   'Tips Report': 'تقرير البقشيش',
   'Service Charge': 'رسوم الخدمة',
   'Shift Summary': 'ملخص الورديات',
   'Food Cost % Trend': 'اتجاه تكلفة الطعام',
   'Cash Flow Forecast': 'توقع التدفق النقدي',
   'Tax Compliance': 'الالتزام الضريبي',
   'Audit Trail': 'سجل التدقيق',
   'Break-Even Analysis': 'تحليل نقطة التعادل',
   'Payment Reconciliation': 'مطابقة المدفوعات',
   'Shift Profitability': 'ربحية الورديات',
   'COGS & Margin': 'تكلفة البضاعة والهامش',
   'Stock Movement': 'حركة المخزون',
   'Stock Counts': 'تقارير الجرد',
   'Waste/Loss Log': 'سجل الهدر والعجز',
   'Reorder Alerts': 'تنبيهات إعادة الطلب',
   'Expiring Batches': 'تشغيلات قرب الانتهاء',
   'Actual vs Theoretical': 'الفعلي مقابل النظري',
   'Purchase History': 'سجل المشتريات',
   'Purchase Orders': 'أوامر الشراء',
   'Suppliers': 'الموردون',
   'Production Batches': 'تشغيلات الإنتاج',
   'Inventory Valuation': 'تقييم المخزون',
   'Supplier Price Tracking': 'متابعة أسعار الموردين',
   'Recipe Cost Alerts': 'تنبيهات تكلفة الوصفات',
   'ABC Classification': 'تصنيف ABC للمخزون',
   'Dead Stock': 'المخزون الراكد',
   'Negative Stock': 'أرصدة سالبة (بيع زيادة)',
   'Optimal Pricing': 'التسعير الأمثل',
   'HR Executive Summary': 'الملخص التنفيذي للموارد البشرية',
   'Payroll Summary': 'ملخص الرواتب',
   'Payroll Ledger': 'كشف استحقاقات الموظفين',
   'Attendance & Delays': 'الحضور والتأخير',
   'Attendance Exceptions': 'استثناءات الحضور والغياب',
   'Overtime Report': 'تقرير الساعات الإضافية',
   'Staff Cost %': 'تكلفة العمالة',
   'Sales per Labor Hour': 'الإيراد لكل ساعة عمل',
   'Employee Productivity': 'إنتاجية الموظفين',
   'Customer LTV': 'القيمة العمرية للعميل',
   'Campaign ROI': 'عائد الحملات',
   'Customer Retention': 'احتفاظ العملاء',
   'New vs Returning': 'عملاء جدد مقابل عائدين',
   'Customer Frequency': 'تكرار زيارات العملاء',
   'Customer Churn': 'تسرب العملاء',
   'Loyalty Points': 'نقاط الولاء',
   'Promotion Impact': 'أثر العروض',
   'Customer Journey Funnel': 'مسار رحلة العميل',
   'Branch Performance': 'أداء الفروع',
   'Order Preparation Time': 'وقت تجهيز الطلب',
   'Delivery Performance': 'أداء التوصيل',
   'Dine-in Tables': 'ترابيزات الصالة',
   'Kitchen Performance': 'أداء المطبخ',
   'Kitchen Staff Performance': 'أداء طاقم المطبخ',
   'Table Turnover': 'دوران الترابيزات',
   'Wait Time': 'وقت الانتظار',
   'Driver Utilization': 'استغلال السائقين',
   'Branch Comparison': 'مقارنة الفروع',
   'Delivery Zone Analytics': 'تحليل مناطق التوصيل',
   'Delivery Cost vs Revenue': 'رسوم التوصيل مقابل الإيراد',
   '3rd Party vs In-House': 'طرف ثالث مقابل توصيل داخلي',
   'Daily Flash Report': 'التقرير اليومي السريع',
   'Demand Forecasting': 'توقع الطلب',
   'Price Elasticity Simulator': 'محاكي مرونة الأسعار',
   'Anomaly Detection': 'تقرير الفحص',
   'Channel Mix Trend': 'اتجاه قنوات البيع',
   'Treasury Cashbox': 'صندوق الخزينة',
   'Custody Statement': 'كشف العهد',
   'Supplier Invoices': 'فواتير الموردين',
   'Butchery Yield': 'ناتج التقطيع (بوتشري)',
   'Inter-Branch Transfers': 'تحويلات الفروع',
   'GRN Variance': 'فروقات الاستلام',
   'Reservations & No-Show': 'الحجوزات وعدم الحضور',
   'Driver COD Settlement': 'تحصيل السائقين (COD)',
   'Approval SLA': 'موافقات وزمن الاعتماد',
   'Platform Commissions': 'عمولات المنصات',
   'Complaints & SLA': 'الشكاوى وزمن الحل',
   'Coupon Usage': 'استخدام الكوبونات',
   'Leave & Absence': 'الإجازات والغياب',
   'Shift Tasks Completion': 'مهام الورديات',
   'Balance Sheet': 'الميزانية العمومية',
   'E-Invoice Rejections': 'الفواتير الإلكترونية المرفوضة',
   'Day-Close Variances': 'فروقات إقفال اليوم',
   'Production Cost Variance': 'انحراف تكلفة التشغيل',
   'Headcount & Turnover': 'القوى العاملة والدوران',
   'WhatsApp Inbox': 'صندوق واتساب',
   'User Activity Log': 'سجل نشاط المستخدمين',
   'Delivery SLA Alerts': 'تنبيهات SLA للتوصيل',
};

export const getReportDisplayLabel = (label: string) => REPORT_DISPLAY_LABELS[label] || label;

export const WEEK_DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
export const HOURS = Array.from({ length: 24 }, (_, hour) => hour);

/** 0–23 → readable 12-hour label: "7 AM" / "7 PM" (en) or "7 ص" / "7 م" (ar). */
export const formatHourLabel = (hour: unknown, lang: 'ar' | 'en' = 'en'): string => {
   const h = ((Number(hour) % 24) + 24) % 24;
   if (!Number.isFinite(h)) return String(hour ?? '');
   const h12 = h % 12 === 0 ? 12 : h % 12;
   const suffix = lang === 'ar' ? (h < 12 ? 'ص' : 'م') : (h < 12 ? 'AM' : 'PM');
   return `${h12} ${suffix}`;
};

export const getExportReportType = (sub: string): string => {
   const map: Record<string, string> = {
      'Trial Balance': 'TRIAL_BALANCE', 'Expense Report': 'EXPENSE_REPORT', 'Top Expenses': 'TOP_EXPENSES', 'Profit & Loss (P&L)': 'PROFIT_LOSS',
       'Stock Movement': 'STOCK_MOVEMENTS', 'Stock Counts': 'STOCK_COUNTS', 'Waste/Loss Log': 'WASTE_LOSS', 'Reorder Alerts': 'REORDER_ALERTS',
      'Expiring Batches': 'EXPIRING_BATCHES', 'HR Executive Summary': 'PAYROLL', 'Payroll Summary': 'PAYROLL', 'Payroll Ledger': 'PAYROLL', 'Attendance & Delays': 'ATTENDANCE',
      'Attendance Exceptions': 'ATTENDANCE', 'Overtime Report': 'OVERTIME', 'Customer LTV': 'CUSTOMER_LTV', 'Campaign ROI': 'CAMPAIGN_ROI',
      'Branch Performance': 'BRANCH_PERFORMANCE', 'Order Preparation Time': 'ORDER_PREP_TIME',
      'Sales by Order Type': 'SALES_BY_ORDER_TYPE', 'Sales by Item': 'SALES_BY_ITEM', 'Sales by Category': 'SALES_BY_CATEGORY',
      'Discounts': 'DISCOUNT_ANALYSIS', 'Cancelled Orders': 'CANCELLED_ORDERS', 'Delivery Performance': 'DELIVERY_PERFORMANCE',
      'Sales by Source': 'SALES_BY_SOURCE', 'Dine-in Tables': 'DINE_IN_TABLES',
      'Peak Hours Heatmap': 'PEAK_HOURS_HEATMAP', 'Modifier Sales': 'MODIFIER_SALES', 'Avg Ticket Trend': 'AVG_TICKET_TREND',
      'Sales Comparison': 'SALES_COMPARISON', 'Slow-Moving Items': 'SLOW_MOVING_ITEMS', 'Revenue by Weekday': 'REVENUE_BY_WEEKDAY',
      'Void Items Log': 'VOID_ITEMS', 'Tips Report': 'TIPS_REPORT', 'Service Charge': 'SERVICE_CHARGE',
      'Shift Summary': 'SHIFT_SUMMARY', 'Actual vs Theoretical': 'ACTUAL_VS_THEORETICAL', 'Purchase History': 'PURCHASE_HISTORY',
      'Inventory Valuation': 'INVENTORY_VALUATION', 'Staff Cost %': 'STAFF_COST_VS_REVENUE', 'Sales per Labor Hour': 'SALES_PER_LABOR_HOUR',
      'Customer Retention': 'CUSTOMER_RETENTION', 'New vs Returning': 'NEW_VS_RETURNING', 'Customer Frequency': 'CUSTOMER_FREQUENCY',
      'Kitchen Performance': 'KITCHEN_PERFORMANCE', 'Kitchen Staff Performance': 'KITCHEN_STAFF_PERFORMANCE', 'Menu Engineering': 'MENU_ENGINEERING', 'Daypart Analysis': 'DAYPART_ANALYSIS',
      'Basket Analysis': 'BASKET_ANALYSIS', 'Seasonality': 'SEASONALITY', 'Online vs Offline': 'ONLINE_VS_OFFLINE',
      'Food Cost % Trend': 'FOOD_COST_TREND', 'Tax Compliance': 'TAX_COMPLIANCE', 'Audit Trail': 'AUDIT_TRAIL',
      'Cash Flow Forecast': 'CASH_FLOW_FORECAST', 'Supplier Price Tracking': 'SUPPLIER_PRICE_TRACKING',
      'Recipe Cost Alerts': 'RECIPE_COST_ALERTS', 'ABC Classification': 'ABC_CLASSIFICATION',
      'Employee Productivity': 'EMPLOYEE_PRODUCTIVITY', 'Customer Churn': 'CUSTOMER_CHURN',
      'Loyalty Points': 'LOYALTY_POINTS', 'Promotion Impact': 'PROMOTION_IMPACT',
      'Table Turnover': 'TABLE_TURNOVER', 'Wait Time': 'WAIT_TIME',
      'Driver Utilization': 'DRIVER_UTILIZATION', 'Branch Comparison': 'BRANCH_COMPARISON',
      'Demand Forecasting': 'DEMAND_FORECAST', 'Price Elasticity Simulator': 'PRICE_ELASTICITY',
      'Menu Cannibalization': 'MENU_CANNIBALIZATION', 'Anomaly Detection': 'ANOMALY_DETECTION',
      'Break-Even Analysis': 'BREAK_EVEN', 'Payment Reconciliation': 'PAYMENT_RECONCILIATION',
      'Daily Flash Report': 'DAILY_FLASH', 'Menu Item Lifecycle': 'MENU_LIFECYCLE',
      'Category Contribution': 'CATEGORY_CONTRIBUTION', 'Shift Profitability': 'SHIFT_PROFITABILITY',
      'Delivery Zone Analytics': 'DELIVERY_ZONE', 'Delivery Cost vs Revenue': 'DELIVERY_COST_REVENUE',
      'Customer Journey Funnel': 'CUSTOMER_JOURNEY', 'Channel Mix Trend': 'CHANNEL_MIX',
      'Optimal Pricing': 'OPTIMAL_PRICING', '3rd Party vs In-House': 'THIRD_PARTY_VS_INHOUSE',
      'Time-to-First-Order': 'TIME_TO_FIRST_ORDER',
      'Treasury Cashbox': 'TREASURY_CASHBOX', 'Custody Statement': 'CUSTODY_STATEMENT',
      'Supplier Invoices': 'SUPPLIER_INVOICES', 'Butchery Yield': 'BUTCHERY_YIELD',
      'Inter-Branch Transfers': 'INTER_BRANCH_TRANSFERS', 'GRN Variance': 'GRN_VARIANCE',
      'Reservations & No-Show': 'RESERVATIONS_NOSHOW', 'Driver COD Settlement': 'DRIVER_COD',
      'Approval SLA': 'APPROVAL_SLA', 'Platform Commissions': 'PLATFORM_COMMISSIONS',
      'Complaints & SLA': 'COMPLAINTS_SLA', 'Coupon Usage': 'COUPON_USAGE',
      'Leave & Absence': 'LEAVE_ABSENCE', 'Shift Tasks Completion': 'SHIFT_TASKS',
      'Balance Sheet': 'BALANCE_SHEET', 'E-Invoice Rejections': 'EINVOICE_REJECTIONS',
      'Day-Close Variances': 'DAYCLOSE_VARIANCES', 'Production Cost Variance': 'PROD_COST_VARIANCE',
      'Headcount & Turnover': 'HEADCOUNT_TURNOVER', 'WhatsApp Inbox': 'WHATSAPP_INBOX',
      'User Activity Log': 'USER_ACTIVITY', 'Delivery SLA Alerts': 'DELIVERY_SLA',
   };
   return map[sub] || sub
      .toUpperCase()
      .replace(/[^A-Z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '');
};

export const SUPPORTED_TABULAR_EXPORT_TYPES = new Set([
   'DAILY_SALES',
   'HOURLY_TRENDS',
   'CASHIER_SUMMARY',
   'REFUNDS',
   'TRIAL_BALANCE',
   'TOP_EXPENSES',
   'EXPENSE_REPORT',
   'PROFIT_LOSS',
   'Z_REPORT_FISCAL',
   'STOCK_MOVEMENTS',
   'STOCK_COUNTS',
   'WASTE_LOSS',
   'REORDER_ALERTS',
   'EXPIRING_BATCHES',
   'PAYROLL',
   'ATTENDANCE',
   'OVERTIME',
   'CUSTOMER_LTV',
   'CAMPAIGN_ROI',
   'BRANCH_PERFORMANCE',
   'ORDER_PREP_TIME',
   'SALES_BY_ORDER_TYPE',
   'SALES_BY_ITEM',
   'SALES_BY_CATEGORY',
   'DISCOUNT_ANALYSIS',
   'CANCELLED_ORDERS',
   'DELIVERY_PERFORMANCE',
   'SALES_BY_SOURCE',
   'DINE_IN_TABLES',
   'PEAK_HOURS_HEATMAP',
   'MODIFIER_SALES',
   'AVG_TICKET_TREND',
   'SALES_COMPARISON',
   'SLOW_MOVING_ITEMS',
   'REVENUE_BY_WEEKDAY',
   'VOID_ITEMS',
   'TIPS_REPORT',
   'SERVICE_CHARGE',
   'SHIFT_SUMMARY',
   'ACTUAL_VS_THEORETICAL',
   'PURCHASE_HISTORY',
   'PRODUCTION_BATCHES',
   'SUPPLIERS',
   'PURCHASE_ORDERS',
   'INVENTORY_VALUATION',
   'STAFF_COST_VS_REVENUE',
   'SALES_PER_LABOR_HOUR',
   'CUSTOMER_RETENTION',
   'NEW_VS_RETURNING',
   'CUSTOMER_FREQUENCY',
   'KITCHEN_PERFORMANCE',
   'MENU_ENGINEERING',
   'DAYPART_ANALYSIS',
   'BASKET_ANALYSIS',
   'SEASONALITY',
   'ONLINE_VS_OFFLINE',
   'FOOD_COST_TREND',
   'TAX_COMPLIANCE',
   'AUDIT_TRAIL',
   'CASH_FLOW_FORECAST',
   'SUPPLIER_PRICE_TRACKING',
   'RECIPE_COST_ALERTS',
   'ABC_CLASSIFICATION',
   'EMPLOYEE_PRODUCTIVITY',
   'CUSTOMER_CHURN',
   'LOYALTY_POINTS',
   'PROMOTION_IMPACT',
   'TABLE_TURNOVER',
   'WAIT_TIME',
   'DRIVER_UTILIZATION',
   'BRANCH_COMPARISON',
   'PRICE_ELASTICITY',
   'MENU_CANNIBALIZATION',
   'ANOMALY_DETECTION',
   'BREAK_EVEN',
   'PAYMENT_RECONCILIATION',
   'DAILY_FLASH',
   'MENU_LIFECYCLE',
   'CATEGORY_CONTRIBUTION',
   'SHIFT_PROFITABILITY',
   'DELIVERY_ZONE',
   'DELIVERY_COST_REVENUE',
   'CUSTOMER_JOURNEY',
   'CHANNEL_MIX',
   'OPTIMAL_PRICING',
   'THIRD_PARTY_VS_INHOUSE',
   'TIME_TO_FIRST_ORDER',
   'COGS_MARGIN',
   'PAYMENT_MIX',
]);

export const isTabularExportSupported = (sub: string) =>
   SUPPORTED_TABULAR_EXPORT_TYPES.has(getExportReportType(sub));

export const downloadBlob = (blob: Blob, filename: string) => {
   const url = URL.createObjectURL(blob);
   const anchor = document.createElement('a');
   anchor.href = url;
   anchor.download = filename;
   document.body.appendChild(anchor);
   anchor.click();
   anchor.remove();
   URL.revokeObjectURL(url);
};
