import React, { useState, useRef, useEffect } from 'react';
import { Download, FileSpreadsheet, FileText, X } from 'lucide-react';

type Column = {
    key: string;
    label: string;
    format?: (val: any) => string;
};

interface ExportButtonProps {
    data: Record<string, any>[];
    columns: Column[];
    filename?: string;
    title?: string;
    className?: string;
}

const toCSV = (data: Record<string, any>[], columns: Column[]): string => {
    const header = columns.map(c => `"${c.label}"`).join(',');
    const rows = data.map(row =>
        columns.map(c => {
            const val = c.format ? c.format(row[c.key]) : (row[c.key] ?? '');
            return `"${String(val).replace(/"/g, '""')}"`;
        }).join(',')
    );
    return [header, ...rows].join('\n');
};

const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob(['\ufeff' + content], { type: `${mimeType};charset=utf-8;` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

const ExportButton: React.FC<ExportButtonProps> = ({
    data,
    columns,
    filename = 'export',
    title = 'Export Data',
    className = '',
}) => {
    const [showMenu, setShowMenu] = useState(false);
    const menuRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handler = (e: MouseEvent) => {
            if (menuRef.current && !menuRef.current.contains(e.target as Node)) setShowMenu(false);
        };
        if (showMenu) document.addEventListener('mousedown', handler);
        return () => document.removeEventListener('mousedown', handler);
    }, [showMenu]);

    const exportCSV = () => {
        const csv = toCSV(data, columns);
        downloadFile(csv, `${filename}_${new Date().toISOString().slice(0, 10)}.csv`, 'text/csv');
        setShowMenu(false);
    };

    const exportHTML = () => {
        const styles = `
            <style>
                body { font-family: 'Tajawal', system-ui, sans-serif; margin: 2rem; }
                h1 { font-family: 'Cairo', system-ui, sans-serif; font-size: 1.5rem; margin-bottom: 1rem; color: #1e293b; }
                table { border-collapse: collapse; width: 100%; font-size: 12px; }
                th { background: #1e293b; color: white; padding: 10px 14px; text-align: left; font-weight: 700; text-transform: uppercase; font-size: 10px; letter-spacing: 0.05em; }
                td { padding: 8px 14px; border-bottom: 1px solid #e2e8f0; }
                tr:nth-child(even) { background: #f8fafc; }
                .footer { margin-top: 2rem; font-size: 10px; color: #94a3b8; }
            </style>
        `;
        const headerCells = columns.map(c => `<th>${c.label}</th>`).join('');
        const bodyRows = data.map(row =>
            `<tr>${columns.map(c => {
                const val = c.format ? c.format(row[c.key]) : (row[c.key] ?? '');
                return `<td>${val}</td>`;
            }).join('')}</tr>`
        ).join('');

        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>${styles}</head><body>
            <h1>${title}</h1>
            <p style="color:#64748b;font-size:11px;margin-bottom:1rem;">${data.length} records · exported ${new Date().toLocaleString()}</p>
            <table><thead><tr>${headerCells}</tr></thead><tbody>${bodyRows}</tbody></table>
            <div class="footer">Generated by Coduis Zen · ${new Date().toISOString()}</div>
        </body></html>`;

        const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const win = window.open(url, '_blank');
        if (win) {
            win.onload = () => {
                win.print();
                URL.revokeObjectURL(url);
            };
        }
        setShowMenu(false);
    };

    if (data.length === 0) return null;

    return (
        <div ref={menuRef} className={`relative inline-block ${className}`}>
            <button onClick={() => setShowMenu(!showMenu)}
                className="flex items-center gap-2 px-4 py-2.5 bg-card border border-border rounded-xl text-[10px] font-black text-muted uppercase tracking-widest hover:text-main hover:border-primary/40 transition-all shadow-sm">
                <Download size={14} /> Export
            </button>

            {showMenu && (
                <div className="absolute top-full right-0 mt-2 w-48 bg-card border border-border rounded-xl shadow-2xl overflow-hidden z-50 animate-in slide-in-from-top-2 duration-200">
                    <div className="p-2 border-b border-border/50 flex items-center justify-between px-3">
                        <span className="text-[9px] font-black text-muted uppercase tracking-widest">Export As</span>
                        <button onClick={() => setShowMenu(false)} className="text-muted hover:text-main"><X size={12} /></button>
                    </div>
                    <div className="p-1">
                        <button onClick={exportCSV}
                            className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-xs font-bold text-main hover:bg-elevated/60 transition-colors text-left">
                            <FileSpreadsheet size={16} className="text-emerald-500" />
                            <div>
                                <p className="font-black text-[10px]">CSV / Excel</p>
                                <p className="text-[8px] text-muted">Spreadsheet compatible</p>
                            </div>
                        </button>
                        <button onClick={exportHTML}
                            className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-xs font-bold text-main hover:bg-elevated/60 transition-colors text-left">
                            <FileText size={16} className="text-blue-500" />
                            <div>
                                <p className="font-black text-[10px]">Print / PDF</p>
                                <p className="text-[8px] text-muted">Print dialog for PDF</p>
                            </div>
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ExportButton;
