import { Order } from '../types';

/**
 * FISCAL SERVICE
 * Prepares data for Egyptian Tax Authority (ETA) E-Receipt Integration (v1.0)
 */
export const fiscalService = {
    /**
     * Transforms an Order into ETA-compliant JSON
     * Based on public API specs for "E-Receipt" (بيانات الفاتورة الإلكترونية)
     */
    prepareETAReceipt: (order: Order) => {
        return {
            header: {
                dateTimeIssued: order.createdAt.toISOString(),
                receiptNumber: order.id,
                uuid: "", // To be generated by ETA SDK/Bridge
                previousUUID: "",
                referenceOldReceiptNumber: ""
            },
            seller: {
                rin: "123-456-789", // Egyptian Tax Registration Number
                companyTradeName: "Restaurant Enterprise",
                branchCode: "0",
                address: {
                    country: "EG",
                    governate: "Cairo",
                    city: "Cairo",
                    street: "90th St",
                    buildingNumber: "Business Tower"
                }
            },
            buyer: {
                type: order.customerPhone ? "P" : "F", // Person or Foreigner/Default
                id: order.customerPhone || "000000000",
                name: order.customerName || "Walk-in Customer"
            },
            itemData: order.items?.map(item => ({
                description: item.name,
                itemType: "GS1",
                itemCode: "10001234", // In real app, this is the GS1 mapped code
                unitType: "EA",
                quantity: item.quantity,
                unitPrice: item.price,
                netSale: item.price * item.quantity,
                totalSale: item.price * item.quantity,
                total: (item.price * item.quantity) * 1.14, // 14% VAT assumed
                taxableItems: [
                    {
                        taxType: "T1",
                        amount: (item.price * item.quantity) * 0.14,
                        subType: "V001",
                        rate: 14
                    }
                ]
            })) || [],
            totalSales: order.total,
            totalVAT: order.tax,
            netAmount: order.subtotal,
            totalAmount: order.total,
            paymentMethod: order.paymentMethod === 'CASH' ? 'C' : 'K' // Cash or Card
        };
    },

    /**
     * Simulation of pushing to ETA Portal
     */
    submitToETA: async (payload: any) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    success: true,
                    submissionId: "ETA-" + Math.random().toString(36).substr(2, 9),
                    qrCode: "https://eta.gov.eg/verify/" + payload.header.receiptNumber
                });
            }, 1500);
        });
    }
};
