import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 01 · AURORA GLASS ──────────────────────────────────────────────
// Premium futuristic SaaS: controlled glass, luminous borders, floating
// layered surfaces. Glass is strategic (cards/overlays), never full-app.
export const auroraGlassTheme: ThemeConfig = {
    id: 'aurora-glass',
    name: 'Aurora Glass',
    description: 'Premium futuristic SaaS: atmospheric glass, luminous borders, floating depth',
    tags: ['Glass', 'Atmospheric', 'Premium SaaS', 'Luminous', 'Layered'],
    shape: { radius: '16px', radiusSm: '10px', radiusLg: '22px', radiusXl: '30px' },
    surfaces: { blur: '24px', surfaceOpacity: 0.68, borderWidth: '1px', borderOpacity: 0.55 },
    shadows: {
        card: '0 8px 28px rgba(79, 70, 229, 0.12), 0 2px 6px rgba(15, 23, 42, 0.06)',
        hover: '0 16px 44px rgba(79, 70, 229, 0.20), 0 4px 12px rgba(15, 23, 42, 0.08)',
        elevated: '0 28px 70px rgba(79, 70, 229, 0.25), inset 0 1px 0 rgba(255,255,255,0.35)',
    },
    motion: { style: 'smooth', easing: 'cubic-bezier(0.22, 1, 0.36, 1)', duration: '220ms', durationSlow: '480ms' },
    typography: { fontWeight: 400, headingWeight: 700, letterSpacing: '0em' },
    spacing: { unit: '1rem', density: 1, gap: '1rem', sectionGap: '1.75rem' },
    components: {
        button: { variant: 'glass', height: '2.75rem', padding: '0.6rem 1.5rem' },
        card: { variant: 'glass' },
        sidebar: { variant: 'floating', width: '264px', collapsedWidth: '72px' },
        table: { density: 'comfortable', rowHeight: '3.25rem' },
        input: { variant: 'glass', height: '2.75rem' },
        modal: { variant: 'floating' },
    },
    layout: { sidebarStyle: 'floating', cardStyle: 'glass', density: 'normal', containerPadding: '1.75rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '16px',
        lineHeight: '1.5',
        focusRingWidth: '3px',
        overlayOpacity: '0.45',
    },
    semantic,
    interaction: {
        intensity: 'standard',
        fast: '140ms',
        normal: '220ms',
        slow: '480ms',
        easeStandard: 'cubic-bezier(0.22, 1, 0.36, 1)',
        easeEmphasized: 'cubic-bezier(0.22, 1, 0.36, 1)',
        easeEnter: 'cubic-bezier(0.22, 1, 0.36, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 0.2, 1)',
        hoverDistance: '3px',
        pressScale: '0.98',
        hoverScale: '1.01',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
