import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 08 · BENTO / MODERN SAAS ────────────────────────────────────────
// Modular startup SaaS: bento rhythm, strong section spacing, clean surfaces,
// smooth card movement. Bright premium light, deep productivity dark.
export const bentoSaasTheme: ThemeConfig = {
    id: 'bento-saas',
    name: 'Bento SaaS',
    description: 'Modular productivity SaaS: bento rhythm, clean hierarchy, smooth card play',
    tags: ['Bento', 'SaaS', 'Modular', 'Startup', 'Clean'],
    shape: { radius: '18px', radiusSm: '12px', radiusLg: '24px', radiusXl: '32px' },
    surfaces: { blur: '12px', surfaceOpacity: 0.94, borderWidth: '1px', borderOpacity: 0.5 },
    shadows: {
        card: '0 2px 8px rgba(30, 27, 75, 0.06), 0 12px 32px -12px rgba(30, 27, 75, 0.18)',
        hover: '0 6px 16px rgba(30, 27, 75, 0.10), 0 20px 44px -12px rgba(30, 27, 75, 0.24)',
        elevated: '0 24px 64px -16px rgba(30, 27, 75, 0.30)',
    },
    motion: { style: 'smooth', easing: 'cubic-bezier(0.21, 0.9, 0.35, 1)', duration: '200ms', durationSlow: '400ms' },
    typography: { fontWeight: 400, headingWeight: 700, letterSpacing: '-0.01em' },
    spacing: { unit: '1rem', density: 1, gap: '1.1rem', sectionGap: '2rem' },
    components: {
        button: { variant: 'soft', height: '2.75rem', padding: '0.6rem 1.5rem' },
        card: { variant: 'elevated' },
        sidebar: { variant: 'floating', width: '260px', collapsedWidth: '72px' },
        table: { density: 'comfortable', rowHeight: '3rem' },
        input: { variant: 'filled', height: '2.75rem' },
        modal: { variant: 'floating' },
    },
    layout: { sidebarStyle: 'floating', cardStyle: 'elevated', density: 'normal', containerPadding: '1.75rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '16px',
        lineHeight: '1.5',
        focusRingWidth: '3px',
        overlayOpacity: '0.45',
    },
    semantic,
    interaction: {
        intensity: 'standard',
        fast: '130ms',
        normal: '200ms',
        slow: '400ms',
        easeStandard: 'cubic-bezier(0.21, 0.9, 0.35, 1)',
        easeEmphasized: 'cubic-bezier(0.21, 0.9, 0.35, 1)',
        easeEnter: 'cubic-bezier(0.21, 0.9, 0.35, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
        hoverDistance: '3px',
        pressScale: '0.98',
        hoverScale: '1.01',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
