import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 05 · EDITORIAL LUXURY ───────────────────────────────────────────
// High-end publication / premium hospitality dashboard: typography-led,
// generous whitespace, hairline dividers, restrained radius. Slow elegant
// motion, zero gimmicks. Serif display voice distinguishes it instantly.
export const editorialLuxuryTheme: ThemeConfig = {
    id: 'editorial-luxury',
    name: 'Editorial Luxury',
    description: 'Publication-grade luxury: typographic hierarchy, hairlines, paper surfaces, slow grace',
    tags: ['Editorial', 'Luxury', 'Typography', 'Paper', 'Refined'],
    shape: { radius: '4px', radiusSm: '2px', radiusLg: '6px', radiusXl: '8px' },
    surfaces: { blur: '0px', surfaceOpacity: 1, borderWidth: '1px', borderOpacity: 0.75 },
    shadows: {
        card: '0 1px 0 rgba(60, 45, 20, 0.08)',
        hover: '0 10px 30px rgba(60, 45, 20, 0.12)',
        elevated: '0 24px 60px rgba(60, 45, 20, 0.16)',
    },
    motion: { style: 'decelerate', easing: 'cubic-bezier(0.16, 0.84, 0.3, 1)', duration: '300ms', durationSlow: '600ms' },
    typography: { fontWeight: 400, headingWeight: 700, letterSpacing: '0.02em' },
    spacing: { unit: '1rem', density: 1.1, gap: '1.25rem', sectionGap: '2.5rem' },
    components: {
        button: { variant: 'solid', height: '2.5rem', padding: '0.55rem 1.6rem' },
        card: { variant: 'flat' },
        sidebar: { variant: 'solid', width: '232px', collapsedWidth: '60px' },
        table: { density: 'comfortable', rowHeight: '3.25rem' },
        input: { variant: 'outline', height: '2.5rem' },
        modal: { variant: 'centered' },
    },
    layout: { sidebarStyle: 'solid', cardStyle: 'flat', density: 'spacious', containerPadding: '2.5rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'Georgia, "Times New Roman", serif',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '16px',
        lineHeight: '1.6',
        focusRingWidth: '2px',
        overlayOpacity: '0.5',
    },
    semantic,
    interaction: {
        intensity: 'subtle',
        fast: '180ms',
        normal: '300ms',
        slow: '600ms',
        easeStandard: 'cubic-bezier(0.16, 0.84, 0.3, 1)',
        easeEmphasized: 'cubic-bezier(0.16, 0.84, 0.3, 1)',
        easeEnter: 'cubic-bezier(0.16, 0.84, 0.3, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 0.2, 1)',
        hoverDistance: '1px',
        pressScale: '0.99',
        hoverScale: '1',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
