import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 07 · FUTURE HUD ─────────────────────────────────────────────────
// Advanced operations center: layered panels, HUD indicators, directional
// transitions, careful glow. Professional ERP — never a gaming interface.
export const futureHudTheme: ThemeConfig = {
    id: 'future-hud',
    name: 'Future HUD',
    description: 'Futuristic ops center: layered panels, HUD status, directional motion, precise glow',
    tags: ['HUD', 'Futuristic', 'Ops Center', 'Panels', 'Glow'],
    shape: { radius: '10px', radiusSm: '6px', radiusLg: '14px', radiusXl: '20px' },
    surfaces: { blur: '14px', surfaceOpacity: 0.88, borderWidth: '1px', borderOpacity: 0.65 },
    shadows: {
        card: '0 6px 24px rgba(0,0,0,0.35), 0 0 20px -6px rgba(var(--primary), 0.45)',
        hover: '0 10px 32px rgba(0,0,0,0.40), 0 0 28px -4px rgba(var(--primary), 0.55)',
        elevated: '0 20px 60px rgba(0,0,0,0.50), 0 0 44px -6px rgba(var(--primary), 0.50)',
    },
    motion: { style: 'ease-out', easing: 'cubic-bezier(0, 0, 0.15, 1)', duration: '180ms', durationSlow: '360ms' },
    typography: { fontWeight: 500, headingWeight: 700, letterSpacing: '0.04em' },
    spacing: { unit: '1rem', density: 0.95, gap: '0.9rem', sectionGap: '1.5rem' },
    components: {
        button: { variant: 'solid', height: '2.5rem', padding: '0.55rem 1.4rem' },
        card: { variant: 'elevated' },
        sidebar: { variant: 'floating', width: '256px', collapsedWidth: '68px' },
        table: { density: 'dense', rowHeight: '2.75rem' },
        input: { variant: 'outline', height: '2.5rem' },
        modal: { variant: 'floating' },
    },
    layout: { sidebarStyle: 'floating', cardStyle: 'elevated', density: 'normal', containerPadding: '1.5rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '15px',
        lineHeight: '1.45',
        focusRingWidth: '2px',
        overlayOpacity: '0.6',
    },
    semantic,
    interaction: {
        intensity: 'expressive',
        fast: '120ms',
        normal: '180ms',
        slow: '360ms',
        easeStandard: 'cubic-bezier(0, 0, 0.15, 1)',
        easeEmphasized: 'cubic-bezier(0, 0, 0.15, 1)',
        easeEnter: 'cubic-bezier(0, 0, 0.15, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
        hoverDistance: '2px',
        pressScale: '0.98',
        hoverScale: '1.01',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
