import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 09 · INDUSTRIAL OPERATIONS ──────────────────────────────────────
// Powerful restaurant-ops platform (logistics / warehouse / kitchen grade):
// robust surfaces, strong hierarchy, compact information, visible status.
// Strongest voice on Inventory, KDS, Dispatch, Production.
export const industrialOpsTheme: ThemeConfig = {
    id: 'industrial-ops',
    name: 'Industrial Ops',
    description: 'Heavy-duty operations: sturdy grids, bold status, mechanical clarity for KDS & inventory',
    tags: ['Industrial', 'Operations', 'KDS', 'Warehouse', 'Sturdy'],
    shape: { radius: '6px', radiusSm: '4px', radiusLg: '8px', radiusXl: '12px' },
    surfaces: { blur: '0px', surfaceOpacity: 1, borderWidth: '1px', borderOpacity: 0.9 },
    shadows: {
        card: '0 2px 0 rgba(20, 20, 20, 0.25), 0 4px 12px rgba(0,0,0,0.12)',
        hover: '0 3px 0 rgba(20, 20, 20, 0.30), 0 10px 24px rgba(0,0,0,0.16)',
        elevated: '0 4px 0 rgba(20, 20, 20, 0.30), 0 20px 48px rgba(0,0,0,0.22)',
    },
    motion: { style: 'crisp', easing: 'cubic-bezier(0.25, 0.8, 0.3, 1)', duration: '140ms', durationSlow: '280ms' },
    typography: { fontWeight: 500, headingWeight: 800, letterSpacing: '0.03em' },
    spacing: { unit: '1rem', density: 0.9, gap: '0.8rem', sectionGap: '1.4rem' },
    components: {
        button: { variant: 'solid', height: '2.5rem', padding: '0.55rem 1.4rem' },
        card: { variant: 'flat' },
        sidebar: { variant: 'solid', width: '248px', collapsedWidth: '64px' },
        table: { density: 'dense', rowHeight: '2.75rem' },
        input: { variant: 'outline', height: '2.5rem' },
        modal: { variant: 'centered' },
    },
    layout: { sidebarStyle: 'solid', cardStyle: 'flat', density: 'compact', containerPadding: '1.25rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '15px',
        lineHeight: '1.4',
        focusRingWidth: '3px',
        overlayOpacity: '0.55',
    },
    semantic,
    interaction: {
        intensity: 'standard',
        fast: '100ms',
        normal: '140ms',
        slow: '280ms',
        easeStandard: 'cubic-bezier(0.25, 0.8, 0.3, 1)',
        easeEmphasized: 'cubic-bezier(0.25, 0.8, 0.3, 1)',
        easeEnter: 'cubic-bezier(0.25, 0.8, 0.3, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
        hoverDistance: '1px',
        pressScale: '0.97',
        hoverScale: '1',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
