import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 09 · FLUENT (Windows-11 calm) ───────────────────────────────
// NOTE: keeps the historical 'industrial-ops' id so saved user settings
// keep working — the industrial look itself is fully retired.
// Mica-like layered surfaces, signature 8px geometry, quiet Win11 blue,
// calm ease-out motion. Strongest voice on POS, Dashboard, front-of-house.
export const industrialOpsTheme: ThemeConfig = {
    id: 'industrial-ops',
    name: 'Fluent',
    description: 'Windows-11 calm: soft mica surfaces, 8px geometry, quiet blue focus for POS & dashboard',
    tags: ['Fluent', 'Calm', 'Windows11', 'Mica', 'Minimal'],
    shape: { radius: '8px', radiusSm: '4px', radiusLg: '12px', radiusXl: '16px' },
    surfaces: { blur: '24px', surfaceOpacity: 0.8, borderWidth: '1px', borderOpacity: 0.5 },
    shadows: {
        card: '0 1.6px 3.6px rgba(0,0,0,0.11), 0 6.4px 28.8px rgba(0,0,0,0.08)',
        hover: '0 3.2px 7.2px rgba(0,0,0,0.13), 0 12.8px 28.8px rgba(0,0,0,0.1)',
        elevated: '0 6.4px 14.4px rgba(0,0,0,0.13), 0 25.6px 57.6px rgba(0,0,0,0.14)',
    },
    motion: { style: 'ease-out', easing: 'cubic-bezier(0.33, 1, 0.68, 1)', duration: '200ms', durationSlow: '350ms' },
    typography: { fontWeight: 400, headingWeight: 700, letterSpacing: '0em' },
    spacing: { unit: '1rem', density: 1, gap: '1rem', sectionGap: '1.75rem' },
    components: {
        button: { variant: 'soft', height: '2.5rem', padding: '0.55rem 1.4rem' },
        card: { variant: 'glass' },
        sidebar: { variant: 'floating', width: '248px', collapsedWidth: '64px' },
        table: { density: 'comfortable', rowHeight: '3rem' },
        input: { variant: 'outline', height: '2.5rem' },
        modal: { variant: 'centered' },
    },
    layout: { sidebarStyle: 'floating', cardStyle: 'glass', density: 'normal', containerPadding: '1.5rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '15px',
        lineHeight: '1.55',
        focusRingWidth: '2px',
        overlayOpacity: '0.45',
    },
    semantic,
    interaction: {
        intensity: 'subtle',
        fast: '150ms',
        normal: '200ms',
        slow: '350ms',
        easeStandard: 'cubic-bezier(0.33, 1, 0.68, 1)',
        easeEmphasized: 'cubic-bezier(0.33, 1, 0.68, 1)',
        easeEnter: 'cubic-bezier(0.33, 1, 0.68, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
        hoverDistance: '0px',
        pressScale: '0.98',
        hoverScale: '1',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
