import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 02 · MIDNIGHT COMMAND ──────────────────────────────────────────
// High-end operations platform (Linear-grade): dark-first, extremely clean,
// high density, restrained color. Fast precise motion, minimal animation.
export const midnightCommandTheme: ThemeConfig = {
    id: 'midnight-command',
    name: 'Midnight Command',
    description: 'Professional command center: dense, precise, restrained — dark-first ops console',
    tags: ['Command Center', 'Dense', 'Precise', 'Dark-first', 'Linear-grade'],
    shape: { radius: '8px', radiusSm: '4px', radiusLg: '10px', radiusXl: '14px' },
    surfaces: { blur: '8px', surfaceOpacity: 0.96, borderWidth: '1px', borderOpacity: 0.7 },
    shadows: {
        card: '0 1px 2px rgba(0,0,0,0.25)',
        hover: '0 4px 14px rgba(0,0,0,0.30)',
        elevated: '0 12px 32px rgba(0,0,0,0.40)',
    },
    motion: { style: 'crisp', easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)', duration: '120ms', durationSlow: '240ms' },
    typography: { fontWeight: 400, headingWeight: 600, letterSpacing: '-0.01em' },
    spacing: { unit: '1rem', density: 0.88, gap: '0.75rem', sectionGap: '1.25rem' },
    components: {
        button: { variant: 'solid', height: '2.25rem', padding: '0.4rem 1rem' },
        card: { variant: 'flat' },
        sidebar: { variant: 'solid', width: '240px', collapsedWidth: '60px' },
        table: { density: 'dense', rowHeight: '2.5rem' },
        input: { variant: 'outline', height: '2.25rem' },
        modal: { variant: 'centered' },
    },
    layout: { sidebarStyle: 'solid', cardStyle: 'flat', density: 'compact', containerPadding: '1.25rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '15px',
        lineHeight: '1.4',
        focusRingWidth: '2px',
        overlayOpacity: '0.6',
    },
    semantic,
    interaction: {
        intensity: 'subtle',
        fast: '90ms',
        normal: '120ms',
        slow: '240ms',
        easeStandard: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        easeEmphasized: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        easeEnter: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
        hoverDistance: '1px',
        pressScale: '0.99',
        hoverScale: '1',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
