import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 03 · NEO BRUTAL ────────────────────────────────────────────────
// Bold, expressive, confident: thick borders, hard offset shadows, square
// corners, high contrast. Tactile buttons, structural cards, snappy press.
export const neoBrutalTheme: ThemeConfig = {
    id: 'neo-brutal',
    name: 'Neo Brutal',
    description: 'Bold graphic workspace: thick borders, hard shadows, square geometry, tactile press',
    tags: ['Brutalist', 'Bold', 'Graphic', 'Tactile', 'High-contrast'],
    shape: { radius: '2px', radiusSm: '0px', radiusLg: '4px', radiusXl: '6px' },
    surfaces: { blur: '0px', surfaceOpacity: 1, borderWidth: '2px', borderOpacity: 1 },
    shadows: {
        card: '4px 4px 0 rgba(15, 15, 15, 0.9)',
        hover: '6px 6px 0 rgba(15, 15, 15, 0.9)',
        elevated: '8px 8px 0 rgba(15, 15, 15, 0.9)',
    },
    motion: { style: 'instant', easing: 'cubic-bezier(0.3, 0.9, 0.3, 1)', duration: '110ms', durationSlow: '200ms' },
    typography: { fontWeight: 500, headingWeight: 800, letterSpacing: '0em' },
    spacing: { unit: '1rem', density: 1, gap: '1rem', sectionGap: '1.5rem' },
    components: {
        button: { variant: 'solid', height: '2.75rem', padding: '0.6rem 1.5rem' },
        card: { variant: 'flat' },
        sidebar: { variant: 'solid', width: '248px', collapsedWidth: '64px' },
        table: { density: 'comfortable', rowHeight: '3rem' },
        input: { variant: 'outline', height: '2.75rem' },
        modal: { variant: 'centered' },
    },
    layout: { sidebarStyle: 'solid', cardStyle: 'flat', density: 'normal', containerPadding: '1.5rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '16px',
        lineHeight: '1.45',
        focusRingWidth: '3px',
        overlayOpacity: '0.55',
    },
    semantic,
    interaction: {
        intensity: 'expressive',
        fast: '80ms',
        normal: '110ms',
        slow: '200ms',
        easeStandard: 'cubic-bezier(0.3, 0.9, 0.3, 1)',
        easeEmphasized: 'cubic-bezier(0.3, 0.9, 0.3, 1)',
        easeEnter: 'cubic-bezier(0.3, 0.9, 0.3, 1)',
        easeExit: 'cubic-bezier(0.5, 0, 0.75, 0)',
        hoverDistance: '2px',
        pressScale: '0.96',
        hoverScale: '1',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
