import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 10 · PREMIUM HOSPITALITY ────────────────────────────────────────
// Elegant restaurant hospitality: warmth, quality, premium service. Refined
// surfaces, gold accents, soft lighting. Graceful motion — luxurious yet
// fast enough for service. Evening-atmosphere dark mode.
export const premiumHospitalityTheme: ThemeConfig = {
    id: 'premium-hospitality',
    name: 'Premium Hospitality',
    description: 'Elegant hospitality: warm refinement, gold accents, soft light, graceful pace',
    tags: ['Hospitality', 'Elegant', 'Warm', 'Premium', 'Gold'],
    shape: { radius: '14px', radiusSm: '10px', radiusLg: '20px', radiusXl: '28px' },
    surfaces: { blur: '18px', surfaceOpacity: 0.9, borderWidth: '1px', borderOpacity: 0.55 },
    shadows: {
        card: '0 12px 32px rgba(90, 60, 30, 0.12), 0 2px 6px rgba(90, 60, 30, 0.06)',
        hover: '0 18px 44px rgba(90, 60, 30, 0.18), 0 0 24px -8px rgba(212, 175, 55, 0.35)',
        elevated: '0 30px 70px rgba(90, 60, 30, 0.22), inset 0 1px 0 rgba(255,250,235,0.5)',
    },
    motion: { style: 'decelerate', easing: 'cubic-bezier(0.2, 0.7, 0.3, 1)', duration: '280ms', durationSlow: '560ms' },
    typography: { fontWeight: 400, headingWeight: 700, letterSpacing: '0.015em' },
    spacing: { unit: '1rem', density: 1.05, gap: '1.1rem', sectionGap: '2rem' },
    components: {
        button: { variant: 'solid', height: '2.75rem', padding: '0.65rem 1.7rem' },
        card: { variant: 'elevated' },
        sidebar: { variant: 'floating', width: '264px', collapsedWidth: '72px' },
        table: { density: 'comfortable', rowHeight: '3.25rem' },
        input: { variant: 'outline', height: '2.75rem' },
        modal: { variant: 'floating' },
    },
    layout: { sidebarStyle: 'floating', cardStyle: 'elevated', density: 'normal', containerPadding: '2rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'Georgia, "Times New Roman", serif',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '16px',
        lineHeight: '1.55',
        focusRingWidth: '3px',
        overlayOpacity: '0.5',
    },
    semantic,
    interaction: {
        intensity: 'standard',
        fast: '170ms',
        normal: '280ms',
        slow: '560ms',
        easeStandard: 'cubic-bezier(0.2, 0.7, 0.3, 1)',
        easeEmphasized: 'cubic-bezier(0.2, 0.7, 0.3, 1)',
        easeEnter: 'cubic-bezier(0.2, 0.7, 0.3, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 0.2, 1)',
        hoverDistance: '2px',
        pressScale: '0.98',
        hoverScale: '1.01',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
