import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 04 · SOFT ORGANIC ──────────────────────────────────────────────
// Calm, friendly, human: pill geometry, generous spacing, warm soft depth,
// slightly elastic gentle motion. Soft charcoal dark — never pure black.
export const softOrganicTheme: ThemeConfig = {
    id: 'soft-organic',
    name: 'Soft Organic',
    description: 'Calm human workspace: pill shapes, warm surfaces, gentle elastic motion',
    tags: ['Friendly', 'Rounded', 'Warm', 'Calm', 'Pill'],
    shape: { radius: '24px', radiusSm: '16px', radiusLg: '28px', radiusXl: '36px' },
    surfaces: { blur: '16px', surfaceOpacity: 0.9, borderWidth: '1px', borderOpacity: 0.4 },
    shadows: {
        card: '0 10px 30px rgba(120, 90, 60, 0.10), 0 2px 6px rgba(120, 90, 60, 0.06)',
        hover: '0 16px 40px rgba(120, 90, 60, 0.16), 0 4px 10px rgba(120, 90, 60, 0.08)',
        elevated: '0 24px 60px rgba(120, 90, 60, 0.20)',
    },
    motion: { style: 'elastic', easing: 'cubic-bezier(0.34, 1.3, 0.5, 1)', duration: '260ms', durationSlow: '560ms' },
    typography: { fontWeight: 400, headingWeight: 700, letterSpacing: '0.01em' },
    spacing: { unit: '1rem', density: 1.12, gap: '1.25rem', sectionGap: '2rem' },
    components: {
        button: { variant: 'soft', height: '3rem', padding: '0.7rem 1.9rem' },
        card: { variant: 'elevated' },
        sidebar: { variant: 'floating', width: '272px', collapsedWidth: '76px' },
        table: { density: 'comfortable', rowHeight: '3.5rem' },
        input: { variant: 'filled', height: '3rem' },
        modal: { variant: 'floating' },
    },
    layout: { sidebarStyle: 'floating', cardStyle: 'elevated', density: 'spacious', containerPadding: '2rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSizeBase: '16px',
        lineHeight: '1.55',
        focusRingWidth: '3px',
        overlayOpacity: '0.4',
    },
    semantic,
    interaction: {
        intensity: 'standard',
        fast: '160ms',
        normal: '260ms',
        slow: '560ms',
        easeStandard: 'cubic-bezier(0.34, 1.3, 0.5, 1)',
        easeEmphasized: 'cubic-bezier(0.34, 1.3, 0.5, 1)',
        easeEnter: 'cubic-bezier(0.34, 1.3, 0.5, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 0.2, 1)',
        hoverDistance: '3px',
        pressScale: '0.97',
        hoverScale: '1.015',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
