import type { ThemeConfig } from '../tokens';

const semantic: ThemeConfig['semantic'] = {
    background: 'rgb(var(--bg-app))',
    backgroundSubtle: 'rgb(var(--bg-global))',
    surface: 'rgb(var(--bg-card))',
    surfaceRaised: 'rgb(var(--bg-elevated))',
    surfaceSunken: 'rgb(var(--bg-app))',
    surfaceOverlay: 'var(--theme-popup-bg, rgb(var(--bg-card)))',
    surfaceHover: 'var(--theme-card-hover-bg, rgb(var(--bg-card)))',
    surfaceActive: 'var(--theme-active-bg, rgba(var(--primary), 0.12))',
    textPrimary: 'rgb(var(--text-main))',
    textSecondary: 'rgb(var(--text-muted))',
    textMuted: 'rgb(var(--text-muted))',
    textDisabled: 'rgba(var(--text-muted), 0.55)',
    textInverse: 'rgb(var(--bg-card))',
    border: 'rgb(var(--border-color))',
    borderSubtle: 'rgba(var(--border-color), 0.5)',
    borderStrong: 'rgba(var(--border-color), 0.9)',
    interactivePrimary: 'rgb(var(--primary))',
    interactiveHover: 'rgb(var(--primary-hover))',
    interactiveActive: 'rgb(var(--primary-hover))',
    statusSuccess: 'rgb(var(--success))',
    statusWarning: 'rgb(var(--warning))',
    statusDanger: 'rgb(var(--danger))',
    statusInfo: 'rgb(var(--info))',
    focus: 'var(--theme-focus-ring, rgba(var(--primary), 0.24))',
    selection: 'rgba(var(--primary), 0.18)',
};

// ── THEME 06 · TERMINAL / OPS ─────────────────────────────────────────────
// Modern premium mission-control: technical grid texture, monospaced
// metadata, compact blocks, immediate status. Sharp functional geometry,
// fastest motion in the system. NOT a retro terminal — a refined console.
export const terminalOpsTheme: ThemeConfig = {
    id: 'terminal-ops',
    name: 'Terminal Ops',
    description: 'Mission-control console: mono metadata, grid texture, instant technical feedback',
    tags: ['Terminal', 'Ops', 'Console', 'Mono', 'Technical'],
    shape: { radius: '6px', radiusSm: '3px', radiusLg: '8px', radiusXl: '10px' },
    surfaces: { blur: '0px', surfaceOpacity: 1, borderWidth: '1px', borderOpacity: 0.85 },
    shadows: {
        card: '0 0 0 rgba(0,0,0,0)',
        hover: '0 0 0 1px rgb(var(--primary)), 0 0 18px rgba(var(--primary), 0.25)',
        elevated: '0 8px 24px rgba(0,0,0,0.35), 0 0 0 1px rgb(var(--primary))',
    },
    motion: { style: 'instant', easing: 'cubic-bezier(0.4, 0, 0.2, 1)', duration: '90ms', durationSlow: '180ms' },
    typography: { fontWeight: 500, headingWeight: 700, letterSpacing: '0em' },
    spacing: { unit: '1rem', density: 0.85, gap: '0.65rem', sectionGap: '1.1rem' },
    components: {
        button: { variant: 'solid', height: '2.25rem', padding: '0.4rem 1rem' },
        card: { variant: 'flat' },
        sidebar: { variant: 'solid', width: '232px', collapsedWidth: '56px' },
        table: { density: 'dense', rowHeight: '2.5rem' },
        input: { variant: 'outline', height: '2.25rem' },
        modal: { variant: 'centered' },
    },
    layout: { sidebarStyle: 'solid', cardStyle: 'flat', density: 'compact', containerPadding: '1rem' },
    primitives: {
        fontFamily: 'var(--font-body, Cairo, system-ui, sans-serif)',
        fontDisplay: 'var(--font-heading, Cairo, system-ui, sans-serif)',
        fontMono: '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
        fontSizeBase: '15px',
        lineHeight: '1.4',
        focusRingWidth: '2px',
        overlayOpacity: '0.65',
    },
    semantic,
    interaction: {
        intensity: 'subtle',
        fast: '70ms',
        normal: '90ms',
        slow: '180ms',
        easeStandard: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeEmphasized: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeEnter: 'cubic-bezier(0, 0, 0.2, 1)',
        easeExit: 'cubic-bezier(0.4, 0, 1, 1)',
        hoverDistance: '0px',
        pressScale: '0.98',
        hoverScale: '1',
    },
    effects: {
        pageBackground: 'var(--theme-page-bg)',
        cardBackground: 'var(--theme-card-bg)',
        cardHoverBackground: 'var(--theme-card-hover-bg)',
        railBackground: 'var(--theme-rail-bg)',
        topbarBackground: 'var(--theme-topbar-bg)',
        inputBackground: 'var(--theme-input-bg)',
        tableHeaderBackground: 'var(--theme-table-head-bg)',
        buttonBackground: 'var(--theme-button-bg)',
        focusRing: 'var(--theme-focus-ring)',
    },
};
